# Generated by Django 5.0.7 on 2025-07-31 21:26

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение (до 5MB)', upload_to=gallery.models.image_upload_path, verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('dishes', models.ManyToManyField(blank=True, related_name='gallery_items', to='menu.dish', verbose_name='Связанные блюда')),
            ],
            options={
                'verbose_name': 'Галерейное изображение',
                'verbose_name_plural': 'Галерейные изображения',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['is_featured'], name='gallery_gal_is_feat_d2223a_idx'), models.Index(fields=['created_at'], name='gallery_gal_created_e0a38d_idx')],
            },
        ),
    ]
