# Generated by Django 5.2.4 on 2025-07-31 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(choices=[('CHEF', 'Шеф-повар'), ('SOUS_CHEF', 'Су-шеф'), ('CHEF_DE_PARTIE', 'Шеф де парти'), ('PASTRY_CHEF', 'Кондитер'), ('BARMAN', 'Бармен'), ('SOMMELIER', 'Сомелье'), ('MANAGER', 'Менеджер'), ('HOST', 'Администратор'), ('WAITER', 'Официант'), ('COOK', 'Повар')], max_length=50, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(help_text='Формат: JPG/PNG. Размер: до 2MB', upload_to='team/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.validate_image_file_extension], verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', 'position', 'name'],
            },
        ),
    ]
