# Generated by Django 5.0.7 on 2025-08-02 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер столика')),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Количество мест')),
                ('shape', models.CharField(choices=[('round', 'Круглый'), ('square', 'Квадратный'), ('rectangular', 'Прямоугольный')], max_length=20, verbose_name='Форма')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP-столик')),
                ('x_pos', models.FloatField(verbose_name='Позиция X на схеме')),
                ('y_pos', models.FloatField(verbose_name='Позиция Y на схеме')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Дата брони')),
                ('time', models.TimeField(verbose_name='Время брони')),
                ('duration', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Длительность (часы)')),
                ('guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество гостей')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.table', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('table', 'date', 'time'), name='unique_reservation'),
        ),
    ]
