# Generated by Django 5.2.4 on 2025-08-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(choices=[('#4CAF50', 'Зеленый'), ('#2196F3', 'Синий'), ('#FFC107', 'Желтый'), ('#F44336', 'Красный')], default='#4CAF50', max_length=7, verbose_name='Цвет на схеме'),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Для нестандартного расположения', verbose_name='Поворот (градусы)'),
        ),
    ]
