# Generated by Django 5.2.4 on 2025-07-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории меню (например, "Паста", "Пицца")', max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальная часть URL для этой категории', max_length=100, unique=True, verbose_name='URL-адрес')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения категорий (меньше = выше)', verbose_name='Порядок')),
                ('image', models.ImageField(blank=True, help_text='Изображение для категории', null=True, upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['slug'], name='menu_catego_slug_6d0e16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название блюда', max_length=200, verbose_name='Название')),
                ('ingredients', models.TextField(help_text='Список ингредиентов через запятую', verbose_name='Ингредиенты')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=8, verbose_name='Цена')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Вес порции в граммах', null=True, verbose_name='Вес (г)')),
                ('is_vegan', models.BooleanField(default=False, help_text='Отметьте, если блюдо вегетарианское', verbose_name='Вегетарианское')),
                ('is_spicy', models.BooleanField(default=False, help_text='Отметьте, если блюдо острое', verbose_name='Острое')),
                ('is_chefs_choice', models.BooleanField(default=False, help_text='Отметьте, если это блюдо - выбор шефа', verbose_name='Выбор шефа')),
                ('image', models.ImageField(help_text='Фотография готового блюда', upload_to='dishes/%Y/%m/%d/', verbose_name='Фото блюда')),
                ('slug', models.SlugField(help_text='Уникальная часть URL для этого блюда', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Когда блюдо было добавлено в меню', verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Когда блюдо было последний раз изменено', verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли блюдо в меню', verbose_name='Активно')),
                ('category', models.ForeignKey(help_text='К какой категории относится блюдо', on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['-is_chefs_choice', 'category__order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='menu_dish_slug_356d63_idx'), models.Index(fields=['is_chefs_choice'], name='menu_dish_is_chef_a3f5cd_idx'), models.Index(fields=['is_active'], name='menu_dish_is_acti_090208_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive')],
            },
        ),
    ]
