# Generated by Django 5.2.4 on 2025-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать ли категорию в меню', verbose_name='Активна'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='menu_catego_is_acti_949851_idx'),
        ),
    ]
