# Generated by Django 5.2.4 on 2025-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото блюда в формате JPG/PNG', null=True, upload_to='dishes/photos/', verbose_name='Фото блюда'),
        ),
    ]
